---
development:
  NEWS_KEY: This_Is_A_Sample_News_Key
  DB_FILENAME: app/infrastructure/database/local/dev.db

test:
  NEWS_KEY: This_Is_A_Sample_News_Key
  DB_FILENAME: app/infrastructure/database/local/test.db
