---
development:
  NEWS_KEY: This_Is_A_Sample_News_Key
  GLOBAL_GIVING_KEY: This_Is_A_Sample_Global_Giving_Key
  DB_FILENAME: app/infrastructure/database/local/dev.db
  SESSION_SECRET: <some secret>

test:
  NEWS_KEY: This_Is_A_Sample_News_Key
  GLOBAL_GIVING_KEY: This_Is_A_Sample_Global_Giving_Key
  DB_FILENAME: app/infrastructure/database/local/test.db
  SESSION_SECRET: <some secret>
